# Generated by Django 5.1.15 on 2026-09-16 16:19

import core.validators
import verification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(storage=verification.models.PrivateMediaStorage(), upload_to=verification.models.verification_upload_path, validators=[core.validators.validate_document]),
        ),
    ]
