# Generated by Django 5.1.15 on 2026-09-16 12:42

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_classes', to='core.classlevel')),
            ],
            options={
                'verbose_name_plural': 'tutor classes',
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('about', models.TextField(blank=True)),
                ('teaching_methodology', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated', max_length=200)),
                ('achievements', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=120)),
                ('degree', models.CharField(blank=True, max_length=120)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('passing_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('teaching_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline (Home/Local)'), ('BOTH', 'Online & Offline')], default='BOTH', max_length=10)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('teaching_radius_km', models.PositiveSmallIntegerField(default=5)),
                ('hourly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_negotiable', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('boards', models.ManyToManyField(blank=True, related_name='tutors', to='core.board')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutors_based', to='locations.location')),
                ('classes', models.ManyToManyField(related_name='tutors', through='tutors.TutorClass', to='core.classlevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tutorclass',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_classes', to='tutors.tutorprofile'),
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='tutors.tutorprofile')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='tutors/gallery/%Y/%m/', validators=[core.validators.validate_image])),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tutors.tutorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('proficiency', models.CharField(blank=True, max_length=60)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_subjects', to='core.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_subjects', to='tutors.tutorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='tutors', through='tutors.TutorSubject', to='core.subject'),
        ),
        migrations.AddConstraint(
            model_name='tutorclass',
            constraint=models.UniqueConstraint(fields=('tutor', 'class_level'), name='unique_tutor_class'),
        ),
        migrations.AddConstraint(
            model_name='tutoravailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tutoravailability',
            constraint=models.UniqueConstraint(fields=('tutor', 'weekday', 'start_time', 'end_time'), name='unique_tutor_slot'),
        ),
        migrations.AddConstraint(
            model_name='tutorsubject',
            constraint=models.UniqueConstraint(fields=('tutor', 'subject'), name='unique_tutor_subject'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['verification_status', 'is_published'], name='tutors_tuto_verific_337ced_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['average_rating'], name='tutors_tuto_average_2fce51_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['hourly_fee'], name='tutors_tuto_hourly__54ffcd_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['experience_years'], name='tutors_tuto_experie_045505_idx'),
        ),
    ]
