# Generated by Django 5.1.15 on 2026-09-16 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0002_initial'),
        ('parents', '0001_initial'),
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline (Home/Local)'), ('BOTH', 'Online & Offline')], default='BOTH', max_length=10)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferred_schedule', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHING', 'Matching'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=10)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.board')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.studentchild')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classlevel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_requests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('proposed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tutors.tutorprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='marketplace.tutorrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('teaching_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline (Home/Local)'), ('BOTH', 'Online & Offline')], default='BOTH', max_length=10)),
                ('preferred_days', models.CharField(blank=True, max_length=120)),
                ('preferred_time', models.CharField(blank=True, max_length=60)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=10)),
                ('tutor_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, help_text='Set when a parent enquires for a child.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='parents.studentchild')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classlevel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_enquiries', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='tutors.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tutor', 'status'], name='marketplace_tutor_i_7e5b98_idx'), models.Index(fields=['sender', 'status'], name='marketplace_sender__b9a3f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tutors.tutorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tutors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tutor'), name='unique_saved_tutor')],
            },
        ),
        migrations.AddIndex(
            model_name='tutorrequest',
            index=models.Index(fields=['status', 'subject'], name='marketplace_status_3aa81d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tutorapplication',
            constraint=models.UniqueConstraint(fields=('request', 'tutor'), name='unique_request_application'),
        ),
    ]
