# Generated by Django 5.1.15 on 2026-09-16 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('SPAM', 'Spam'), ('FRAUD', 'Fraud'), ('HARASSMENT', 'Harassment'), ('FAKE_INFORMATION', 'Fake information'), ('INAPPROPRIATE_BEHAVIOUR', 'Inappropriate behaviour'), ('OTHER', 'Other')], max_length=24)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=14)),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'target_content_type', 'target_object_id'), name='unique_report_per_target')],
            },
        ),
    ]
