# Generated by Django 5.1.15 on 2026-09-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=10)),
                ('state', models.CharField(default='West Bengal', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'area'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='locations_l_city_3924cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'area'), name='unique_location_city_area')],
            },
        ),
        migrations.CreateModel(
            name='TutorTeachingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_covering', to='locations.location')),
            ],
        ),
    ]
