# Generated by Django 5.1.15 on 2026-09-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorteachingarea',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_areas', to='tutors.tutorprofile'),
        ),
        migrations.AddConstraint(
            model_name='tutorteachingarea',
            constraint=models.UniqueConstraint(fields=('tutor', 'location'), name='unique_tutor_teaching_area'),
        ),
    ]
